FROM apache/airflow:2.10.3-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    dbt-postgres \
    requests \
    pandas \
    sqlalchemy \
    psycopg2-binary \
    faker \
    python-dotenv
